name: Test Action
on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout repo to use the action locally
        uses: actions/checkout@v4.2.2
        
      - name: Check runner environment
        run: |
          echo "Runner is running on: $RUNNER_OS"
          echo "Available disk space:"
          df -h

      - name: Verify Docker installation
        run: docker --version

      - name: Run my own container action
        id: action
        uses: ./  # Указывает, что используется локальный action
        with:
          who-to-greet: '@wulfland'
      
      - name: Output the answer
        run: echo "The answer is ${{ steps.action.outputs.answer }}"
      
      - name: Test the container
        if: ${{ steps.action.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
          exit 1
      
      - name: Notify success
        if: ${{ success() }}
        run: echo "Workflow completed successfully!"

      - name: Notify failure
        if: ${{ failure() }}
        run: echo "Workflow failed!"

